// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package global

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal(in *jlexer.Lexer, out *UpstreamType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "middleware":
			if in.IsNull() {
				in.Skip()
				out.Middleware = nil
			} else {
				in.Delim('[')
				if out.Middleware == nil {
					if !in.IsDelim(']') {
						out.Middleware = make([]ModuleConfig, 0, 2)
					} else {
						out.Middleware = []ModuleConfig{}
					}
				} else {
					out.Middleware = (out.Middleware)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ModuleConfig
					(v1).UnmarshalEasyJSON(in)
					out.Middleware = append(out.Middleware, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "discover":
			(out.Discover).UnmarshalEasyJSON(in)
		case "cache":
			out.Cache = bool(in.Bool())
		case "cache_retry":
			out.CacheRetry = int(in.Int())
		case "load_balance":
			out.LoadBalance = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal(out *jwriter.Writer, in UpstreamType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if len(in.Middleware) != 0 {
		const prefix string = ",\"middleware\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.Middleware {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"discover\":"
		out.RawString(prefix)
		(in.Discover).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"cache\":"
		out.RawString(prefix)
		out.Bool(bool(in.Cache))
	}
	{
		const prefix string = ",\"cache_retry\":"
		out.RawString(prefix)
		out.Int(int(in.CacheRetry))
	}
	if in.LoadBalance != "" {
		const prefix string = ",\"load_balance\":"
		out.RawString(prefix)
		out.String(string(in.LoadBalance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpstreamType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpstreamType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpstreamType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpstreamType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal(l, v)
}
func easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal1(in *jlexer.Lexer, out *ProxyStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "middleware":
			if in.IsNull() {
				in.Skip()
				out.Middleware = nil
			} else {
				in.Delim('[')
				if out.Middleware == nil {
					if !in.IsDelim(']') {
						out.Middleware = make([]ModuleConfig, 0, 2)
					} else {
						out.Middleware = []ModuleConfig{}
					}
				} else {
					out.Middleware = (out.Middleware)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ModuleConfig
					(v4).UnmarshalEasyJSON(in)
					out.Middleware = append(out.Middleware, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "hosts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Hosts = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 string
					v5 = string(in.String())
					(out.Hosts)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		case "routes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Routes = make(map[string]map[string]map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 map[string]map[string]string
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v6 = make(map[string]map[string]string)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v7 map[string]string
							if in.IsNull() {
								in.Skip()
							} else {
								in.Delim('{')
								v7 = make(map[string]string)
								for !in.IsDelim('}') {
									key := string(in.String())
									in.WantColon()
									var v8 string
									v8 = string(in.String())
									(v7)[key] = v8
									in.WantComma()
								}
								in.Delim('}')
							}
							(v6)[key] = v7
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Routes)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		case "upstreams":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Upstreams = make(map[string]UpstreamType)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v9 UpstreamType
					(v9).UnmarshalEasyJSON(in)
					(out.Upstreams)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal1(out *jwriter.Writer, in ProxyStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"middleware\":"
		out.RawString(prefix[1:])
		if in.Middleware == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Middleware {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"hosts\":"
		out.RawString(prefix)
		if in.Hosts == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.Hosts {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.String(string(v12Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"routes\":"
		out.RawString(prefix)
		if in.Routes == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.Routes {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				if v13Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v14First := true
					for v14Name, v14Value := range v13Value {
						if v14First {
							v14First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v14Name))
						out.RawByte(':')
						if v14Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
							out.RawString(`null`)
						} else {
							out.RawByte('{')
							v15First := true
							for v15Name, v15Value := range v14Value {
								if v15First {
									v15First = false
								} else {
									out.RawByte(',')
								}
								out.String(string(v15Name))
								out.RawByte(':')
								out.String(string(v15Value))
							}
							out.RawByte('}')
						}
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"upstreams\":"
		out.RawString(prefix)
		if in.Upstreams == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v16First := true
			for v16Name, v16Value := range in.Upstreams {
				if v16First {
					v16First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v16Name))
				out.RawByte(':')
				(v16Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProxyStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProxyStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProxyStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProxyStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal1(l, v)
}
func easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal2(in *jlexer.Lexer, out *ModuleConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "config":
			out.Config = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal2(out *jwriter.Writer, in ModuleConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"config\":"
		out.RawString(prefix)
		out.String(string(in.Config))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModuleConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModuleConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModuleConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModuleConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal2(l, v)
}
func easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal3(in *jlexer.Lexer, out *EndpointType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "upstream_id":
			out.UpstreamID = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "weight":
			out.Weight = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal3(out *jwriter.Writer, in EndpointType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"upstream_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.UpstreamID))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		out.Int(int(in.Weight))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EndpointType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EndpointType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f2eff5fEncodeGithubComDxvgefTsingGatewayGlobal3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EndpointType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EndpointType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f2eff5fDecodeGithubComDxvgefTsingGatewayGlobal3(l, v)
}
