// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package global

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA1ea4324DecodeGithubComDxvgefTsingGatewayGlobal(in *jlexer.Lexer, out *ModuleConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "config":
			out.Config = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA1ea4324EncodeGithubComDxvgefTsingGatewayGlobal(out *jwriter.Writer, in ModuleConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"config\":"
		out.RawString(prefix)
		out.String(string(in.Config))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModuleConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA1ea4324EncodeGithubComDxvgefTsingGatewayGlobal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModuleConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA1ea4324EncodeGithubComDxvgefTsingGatewayGlobal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModuleConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA1ea4324DecodeGithubComDxvgefTsingGatewayGlobal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModuleConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA1ea4324DecodeGithubComDxvgefTsingGatewayGlobal(l, v)
}
