################################################### 测试
GET http://127.0.0.1/favicon.ic

################################################### 数据管理

### 获取所有数据
GET http://127.0.0.1:10080/data/
SECRET: 123456

### 加载所有数据
POST http://127.0.0.1:10080/data/
SECRET: 123456

### 保存所有数据
PUT http://127.0.0.1:10080/data/
SECRET: 123456

################################################### 主机管理

### 添加主机
POST http://127.0.0.1:10080/hosts/
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

hostname=*&config={"route_group_id":"test","middleware":[{"name":"favicon","config":"{\"status\":204}"}]}

### 设置主机
PUT http://127.0.0.1:10080/hosts/Kg
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

config={"route_group_id":"test_group","middleware":[{"name":"favicon","config":"{\"status\":204}"}]}

### 删除主机
DELETE http://127.0.0.1:10080/hosts/Kg
SECRET: 123456

################################################### 服务管理

### 添加服务
POST http://127.0.0.1:10080/services/
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

id=test_service&static_endpoint=http://127.0.0.1:30080&middleware=[{"name":"set_header","config":"{\"request_header\":{\"X-MYTEST-1\":\"1\",\"X-MYTEST-2\":\"2\"}}"},{"name":"url_rewrite","config":"{\"prefix\":{\"/\":\"/test/\"}}"}]

### 设置服务
PUT http://127.0.0.1:10080/services/dGVzdF9zZXJ2aWNl
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

discover={"name":"tsing_center","config":"{\"addr\":\"http://127.0.0.1:20080\",\"secret\":\"123456\"}"}&middleware=[{"name":"set_header","config":"{\"request_header\":{\"X-MYTEST-1\":\"1\",\"X-MYTEST-2\":\"2\"}}"},{"name":"url_rewrite","config":"{\"prefix\":{\"/\":\"/test/\"}}"}]

### 删除服务
DELETE http://127.0.0.1:10080/services/dGVzdF9zZXJ2aWNl
SECRET: 123456

################################################### 路由管理

### 添加路由
POST http://127.0.0.1:10080/routes/
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

group_id=test_group&path=/*&method=ANY&service_id=test_service

### 设置路由
PUT http://127.0.0.1:10080/routes/dGVzdF9ncm91cA/Lyo/ANY
SECRET: 123456
Content-Type: application/x-www-form-urlencoded

service_id=test_service

### 删除路由
DELETE http://127.0.0.1:10080/routes/dGVzdF9ncm91cA/Lyo/ANY
SECRET: 123456
