// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package url_rewrite

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16d7ec28DecodeLocalMiddlewareCheckJwt(in *jlexer.Lexer, out *CheckJWT) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "source_channel":
			out.SourceChannel = string(in.String())
		case "source_name":
			out.SourceName = string(in.String())
		case "alg":
			out.Alg = string(in.String())
		case "private_key":
			out.PrivateKey = string(in.String())
		case "remote_url":
			out.RemoteURL = string(in.String())
		case "remote_channel":
			out.RemoteChannel = string(in.String())
		case "remote_name":
			out.RemoteName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16d7ec28EncodeLocalMiddlewareCheckJwt(out *jwriter.Writer, in CheckJWT) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"source_channel\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceChannel))
	}
	{
		const prefix string = ",\"source_name\":"
		out.RawString(prefix)
		out.String(string(in.SourceName))
	}
	{
		const prefix string = ",\"alg\":"
		out.RawString(prefix)
		out.String(string(in.Alg))
	}
	if in.PrivateKey != "" {
		const prefix string = ",\"private_key\":"
		out.RawString(prefix)
		out.String(string(in.PrivateKey))
	}
	if in.RemoteURL != "" {
		const prefix string = ",\"remote_url\":"
		out.RawString(prefix)
		out.String(string(in.RemoteURL))
	}
	if in.RemoteChannel != "" {
		const prefix string = ",\"remote_channel\":"
		out.RawString(prefix)
		out.String(string(in.RemoteChannel))
	}
	if in.RemoteName != "" {
		const prefix string = ",\"remote_name\":"
		out.RawString(prefix)
		out.String(string(in.RemoteName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CheckJWT) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16d7ec28EncodeLocalMiddlewareCheckJwt(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CheckJWT) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16d7ec28EncodeLocalMiddlewareCheckJwt(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CheckJWT) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16d7ec28DecodeLocalMiddlewareCheckJwt(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CheckJWT) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16d7ec28DecodeLocalMiddlewareCheckJwt(l, v)
}
