// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cors

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE7f5bc6fDecodeLocalMiddlewareCors(in *jlexer.Lexer, out *CORS) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "allow_origins":
			out.AllowOrigins = string(in.String())
		case "expose_headers":
			out.ExposeHeaders = string(in.String())
		case "allow_credentials":
			out.AllowCredentials = bool(in.Bool())
		case "allow_methods":
			out.AllowMethods = string(in.String())
		case "allow_headers":
			out.AllowHeaders = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE7f5bc6fEncodeLocalMiddlewareCors(out *jwriter.Writer, in CORS) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AllowOrigins != "" {
		const prefix string = ",\"allow_origins\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.AllowOrigins))
	}
	if in.ExposeHeaders != "" {
		const prefix string = ",\"expose_headers\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ExposeHeaders))
	}
	if in.AllowCredentials {
		const prefix string = ",\"allow_credentials\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.AllowCredentials))
	}
	if in.AllowMethods != "" {
		const prefix string = ",\"allow_methods\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AllowMethods))
	}
	if in.AllowHeaders != "" {
		const prefix string = ",\"allow_headers\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AllowHeaders))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CORS) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE7f5bc6fEncodeLocalMiddlewareCors(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CORS) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE7f5bc6fEncodeLocalMiddlewareCors(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CORS) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE7f5bc6fDecodeLocalMiddlewareCors(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CORS) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE7f5bc6fDecodeLocalMiddlewareCors(l, v)
}
