// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package favicon

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC8dfbd0aDecodeGithubComDxvgefTsingGatewayMiddlewareFavicon(in *jlexer.Lexer, out *Favicon) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = int(in.Int())
		case "target":
			out.Target = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8dfbd0aEncodeGithubComDxvgefTsingGatewayMiddlewareFavicon(out *jwriter.Writer, in Favicon) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Status))
	}
	if in.Target != "" {
		const prefix string = ",\"target\":"
		out.RawString(prefix)
		out.String(string(in.Target))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Favicon) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8dfbd0aEncodeGithubComDxvgefTsingGatewayMiddlewareFavicon(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Favicon) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8dfbd0aEncodeGithubComDxvgefTsingGatewayMiddlewareFavicon(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Favicon) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8dfbd0aDecodeGithubComDxvgefTsingGatewayMiddlewareFavicon(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Favicon) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8dfbd0aDecodeGithubComDxvgefTsingGatewayMiddlewareFavicon(l, v)
}
