// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tsing_center

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverEtcd(in *jlexer.Lexer, out *TsingCenter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "etcd_endpoints":
			if in.IsNull() {
				in.Skip()
				out.Addr = nil
			} else {
				in.Delim('[')
				if out.Addr == nil {
					if !in.IsDelim(']') {
						out.Addr = make([]string, 0, 4)
					} else {
						out.Addr = []string{}
					}
				} else {
					out.Addr = (out.Addr)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Addr = append(out.Addr, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "key_prefix":
			out.KeyPrefix = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverEtcd(out *jwriter.Writer, in TsingCenter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"etcd_endpoints\":"
		out.RawString(prefix[1:])
		if in.Addr == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Addr {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"key_prefix\":"
		out.RawString(prefix)
		out.String(string(in.KeyPrefix))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TsingCenter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverEtcd(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TsingCenter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverEtcd(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TsingCenter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverEtcd(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TsingCenter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverEtcd(l, v)
}
