// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tsing_center

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(in *jlexer.Lexer, out *TsingCenter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "addr":
			out.Addr = string(in.String())
		case "secret":
			out.Secret = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(out *jwriter.Writer, in TsingCenter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"addr\":"
		out.RawString(prefix[1:])
		out.String(string(in.Addr))
	}
	{
		const prefix string = ",\"secret\":"
		out.RawString(prefix)
		out.String(string(in.Secret))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TsingCenter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TsingCenter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson16d7ec28EncodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TsingCenter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TsingCenter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson16d7ec28DecodeGithubComDxvgefTsingGatewayDiscoverTsingCenter(l, v)
}
