// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6fc2bfdaDecodeGithubComDxvgefTsingGatewayApi(in *jlexer.Lexer, out *Proxy) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "middleware":
			out.Middleware = string(in.String())
		case "routes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Routes = make(map[string]map[string]map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 map[string]map[string]string
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('{')
						v1 = make(map[string]map[string]string)
						for !in.IsDelim('}') {
							key := string(in.String())
							in.WantColon()
							var v2 map[string]string
							if in.IsNull() {
								in.Skip()
							} else {
								in.Delim('{')
								v2 = make(map[string]string)
								for !in.IsDelim('}') {
									key := string(in.String())
									in.WantColon()
									var v3 string
									v3 = string(in.String())
									(v2)[key] = v3
									in.WantComma()
								}
								in.Delim('}')
							}
							(v1)[key] = v2
							in.WantComma()
						}
						in.Delim('}')
					}
					(out.Routes)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6fc2bfdaEncodeGithubComDxvgefTsingGatewayApi(out *jwriter.Writer, in Proxy) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"middleware\":"
		out.RawString(prefix[1:])
		out.String(string(in.Middleware))
	}
	{
		const prefix string = ",\"routes\":"
		out.RawString(prefix)
		if in.Routes == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Routes {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
					out.RawString(`null`)
				} else {
					out.RawByte('{')
					v5First := true
					for v5Name, v5Value := range v4Value {
						if v5First {
							v5First = false
						} else {
							out.RawByte(',')
						}
						out.String(string(v5Name))
						out.RawByte(':')
						if v5Value == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
							out.RawString(`null`)
						} else {
							out.RawByte('{')
							v6First := true
							for v6Name, v6Value := range v5Value {
								if v6First {
									v6First = false
								} else {
									out.RawByte(',')
								}
								out.String(string(v6Name))
								out.RawByte(':')
								out.String(string(v6Value))
							}
							out.RawByte('}')
						}
					}
					out.RawByte('}')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Proxy) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6fc2bfdaEncodeGithubComDxvgefTsingGatewayApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Proxy) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6fc2bfdaEncodeGithubComDxvgefTsingGatewayApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Proxy) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6fc2bfdaDecodeGithubComDxvgefTsingGatewayApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Proxy) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6fc2bfdaDecodeGithubComDxvgefTsingGatewayApi(l, v)
}
